name: learning the docker action 

on: push 

jobs:
  hello-job-world:
     runs-on: ubuntu-latest
     name: simple hello job 
     steps:
       - name:  Hello world action step
         id: hello 
         uses: actions/hello-world-docker-action@v2
         with:
          who-to-greet: 'Mona the Octocat'

       - name: Get the output time
         run: echo "The time was ${{ steps.hello.outputs.time }}"   
           
